### ISSUE TITLE
Variable interpolation is not translated well

### ISSUE THREAD

**Issue by FokkeZB** [brauliobo/less2sass#10]
Less

```less
@font-face {
    font-family: 'League Spartan';
    src: url('@{ttn-font-path}leaguespartan-bold.eot');
    src: url('@{ttn-font-path}leaguespartan-bold.eot?#iefix') format('embedded-opentype'),
         url('@{ttn-font-path}leaguespartan-bold.woff2') format('woff2'),
         url('@{ttn-font-path}leaguespartan-bold.woff') format('woff'),
         url('@{ttn-font-path}leaguespartan-bold.ttf') format('truetype'),
         url('@{ttn-font-path}leaguespartan-bold.svg#league_spartanbold') format('svg');
    font-weight: bold;
    font-style: normal;
}
```

Current SCSS output

```scss
@font-face {
    font-family: 'League Spartan';
    src: url('${ttn-font-path}leaguespartan-bold.eot');
    src: url('${ttn-font-path}leaguespartan-bold.eot?#iefix') format('embedded-opentype'),
         url('${ttn-font-path}leaguespartan-bold.woff2') format('woff2'),
         url('${ttn-font-path}leaguespartan-bold.woff') format('woff'),
         url('${ttn-font-path}leaguespartan-bold.ttf') format('truetype'),
         url('${ttn-font-path}leaguespartan-bold.svg#league_spartanbold') format('svg');
    font-weight: bold;
    font-style: normal;
}
```

This should be:

```scss
@font-face {
    font-family: 'League Spartan';
    src: url('#{$ttn-font-path}leaguespartan-bold.eot');
    src: url('#{$ttn-font-path}leaguespartan-bold.eot?#iefix') format('embedded-opentype'),
         url('#{$ttn-font-path}leaguespartan-bold.woff2') format('woff2'),
         url('#{$ttn-font-path}leaguespartan-bold.woff') format('woff'),
         url('#{$ttn-font-path}leaguespartan-bold.ttf') format('truetype'),
         url('#{$ttn-font-path}leaguespartan-bold.svg#league_spartanbold') format('svg');
    font-weight: bold;
    font-style: normal;
}
```
